name: splinedist-starter
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-image=0.19
  - black
  - ca-certificates
  - openssl
  - opencv=4.5
  - pip=22.1
  - tensorflow=2.6
  - cudatoolkit>=11
  - cudnn
  - tqdm
  - pip:
    - csbdeep
    - gputools